// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8JpA5mT0n65n2SuTc9AwQGNaI1-6eE1k',
    appId: '1:82168662052:web:e7725edf6b421c4b4070b1',
    messagingSenderId: '82168662052',
    projectId: 'iclean-bce7a',
    authDomain: 'iclean-bce7a.firebaseapp.com',
    storageBucket: 'iclean-bce7a.appspot.com',
    measurementId: 'G-VKQ375ND3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWz_MpBU2vg-zDf8WRq_qmAeIdYIVfQpM',
    appId: '1:82168662052:android:e832a4cf7ff0ef494070b1',
    messagingSenderId: '82168662052',
    projectId: 'iclean-bce7a',
    storageBucket: 'iclean-bce7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOhrNaiyOviNiN6HU0qZdAXbK-zkimK1w',
    appId: '1:82168662052:ios:d10e04acac0adebf4070b1',
    messagingSenderId: '82168662052',
    projectId: 'iclean-bce7a',
    storageBucket: 'iclean-bce7a.appspot.com',
    iosClientId: '82168662052-fu5nh4muh6j8q5db1qujll0ioh2clp86.apps.googleusercontent.com',
    iosBundleId: 'com.example.swdProjectClatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOhrNaiyOviNiN6HU0qZdAXbK-zkimK1w',
    appId: '1:82168662052:ios:d10e04acac0adebf4070b1',
    messagingSenderId: '82168662052',
    projectId: 'iclean-bce7a',
    storageBucket: 'iclean-bce7a.appspot.com',
    iosClientId: '82168662052-fu5nh4muh6j8q5db1qujll0ioh2clp86.apps.googleusercontent.com',
    iosBundleId: 'com.example.swdProjectClatt',
  );
}
